runtime: nodejs22
service: client

build_env_variables:
  NEXT_PUBLIC_API_URL: "https://healthy-one-gram.el.r.appspot.com"
  NEXT_PUBLIC_APP_API_URL: "https://healthy-one-gram.el.r.appspot.com"
  NEXT_PUBLIC_SITE_URL: "https://healthyonegram.com"
  NEXT_PUBLIC_FIREBASE_API_KEY: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_APP_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_VAPID_KEY: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "SET_OPTIONAL_AT_DEPLOY"

env_variables:
  NEXT_PUBLIC_API_URL: "https://healthy-one-gram.el.r.appspot.com"
  NEXT_PUBLIC_APP_API_URL: "https://healthy-one-gram.el.r.appspot.com"
  NEXT_PUBLIC_SITE_URL: "https://healthyonegram.com"
  NEXT_PUBLIC_FIREBASE_API_KEY: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_APP_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_FIREBASE_VAPID_KEY: "SET_OPTIONAL_AT_DEPLOY"
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "SET_OPTIONAL_AT_DEPLOY"
