runtime: nodejs22
service: default

env_variables:
  NODE_ENV: "production"
  MONGO_URI: "SET_AT_DEPLOY"
  ACCESS_TOKEN_SECRET: "SET_AT_DEPLOY"
  REFRESH_TOKEN_SECRET: "SET_AT_DEPLOY"
  CLIENT_URL: "SET_AT_DEPLOY"
  ADMIN_URL: "SET_AT_DEPLOY"
  EMAIL: "SET_OPTIONAL_AT_DEPLOY"
  EMAIL_PASSWORD: "SET_OPTIONAL_AT_DEPLOY"
  CLOUDINARY_CLOUD_NAME: "SET_OPTIONAL_AT_DEPLOY"
  CLOUDINARY_API_KEY: "SET_OPTIONAL_AT_DEPLOY"
  CLOUDINARY_API_SECRET: "SET_OPTIONAL_AT_DEPLOY"
  FIREBASE_PROJECT_ID: "SET_OPTIONAL_AT_DEPLOY"
  FIREBASE_CLIENT_EMAIL: "SET_OPTIONAL_AT_DEPLOY"
  FIREBASE_PRIVATE_KEY: "SET_OPTIONAL_AT_DEPLOY"
