import mongoose from "mongoose";

/**
 * Influencer Model
 *
 * Stores influencer/referral partner information
 * Referral links are generated by backend/admin only
 * Influencers cannot create or modify their links
 */
const influencerSchema = new mongoose.Schema(
  {
    // Influencer name/identifier
    name: {
      type: String,
      required: [true, "Influencer name is required"],
      trim: true,
      maxLength: [100, "Name cannot exceed 100 characters"],
    },

    // Email for contact (optional)
    email: {
      type: String,
      trim: true,
      lowercase: true,
      default: null,
    },

    // Phone for contact (optional)
    phone: {
      type: String,
      trim: true,
      default: null,
    },

    // Unique referral code (admin-defined, used in URL)
    code: {
      type: String,
      required: [true, "Referral code is required"],
      unique: true,
      uppercase: true,
      trim: true,
      index: true,
      maxLength: [30, "Code cannot exceed 30 characters"],
      match: [
        /^[A-Z0-9_-]+$/,
        "Code can only contain uppercase letters, numbers, underscores and hyphens",
      ],
    },

    // Discount offered to customers using this referral
    discountType: {
      type: String,
      enum: ["PERCENT", "FLAT"],
      required: true,
      default: "PERCENT",
    },

    discountValue: {
      type: Number,
      required: true,
      min: [0, "Discount value cannot be negative"],
      default: 0,
    },

    // Maximum discount amount (for PERCENT type)
    maxDiscountAmount: {
      type: Number,
      default: null, // null = no limit
      min: 0,
    },

    // Minimum order value to apply discount
    minOrderAmount: {
      type: Number,
      default: 0,
      min: 0,
    },

    // Commission earned by influencer per order
    commissionType: {
      type: String,
      enum: ["PERCENT", "FLAT"],
      required: true,
      default: "PERCENT",
    },

    commissionValue: {
      type: Number,
      required: true,
      min: [0, "Commission value cannot be negative"],
      default: 0,
    },

    // Whether this influencer is active
    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },

    // Expiry date (optional)
    expiresAt: {
      type: Date,
      default: null, // null = never expires
    },

    // Usage tracking
    totalOrders: {
      type: Number,
      default: 0,
      min: 0,
    },

    totalRevenue: {
      type: Number,
      default: 0,
      min: 0,
    },

    totalCommissionEarned: {
      type: Number,
      default: 0,
      min: 0,
    },

    totalCommissionPaid: {
      type: Number,
      default: 0,
      min: 0,
    },

    // Notes (admin use)
    notes: {
      type: String,
      default: "",
      maxLength: 500,
    },

    // Refresh token for influencer portal sessions
    refreshToken: {
      type: String,
      default: "",
    },

    // Created by admin
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true,
  },
);

// Indexes for common queries
influencerSchema.index({ code: 1, isActive: 1 });
influencerSchema.index({ createdAt: -1 });

// Virtual for referral URL (generated by backend)
// Uses SITE_BASE_URL for production, falls back to FRONTEND_URL or localhost
influencerSchema.virtual("referralUrl").get(function () {
  const rawBaseUrl =
    process.env.SITE_BASE_URL ||
    process.env.FRONTEND_URL ||
    "http://localhost:3000";
  const baseUrl = rawBaseUrl.split(",")[0].trim();
  // Ensure no double slashes and proper query param format
  const cleanBaseUrl = baseUrl.replace(/\/$/, "");
  return `${cleanBaseUrl}/?ref=${this.code}`;
});

// Ensure virtuals are included in JSON output
influencerSchema.set("toJSON", { virtuals: true });
influencerSchema.set("toObject", { virtuals: true });

// Static method to validate and get active influencer by code
influencerSchema.statics.findActiveByCode = async function (code) {
  if (!code) return null;

  const influencer = await this.findOne({
    code: code.toUpperCase().trim(),
    isActive: true,
  });

  if (!influencer) return null;

  // Check expiry
  if (influencer.expiresAt && new Date() > influencer.expiresAt) {
    return null;
  }

  return influencer;
};

// Method to calculate discount for an order
influencerSchema.methods.calculateDiscount = function (orderAmount) {
  if (orderAmount < this.minOrderAmount) {
    return 0;
  }

  let discount = 0;

  if (this.discountType === "PERCENT") {
    discount = (orderAmount * this.discountValue) / 100;
    // Apply max discount cap if set
    if (this.maxDiscountAmount && discount > this.maxDiscountAmount) {
      discount = this.maxDiscountAmount;
    }
  } else {
    // FLAT discount
    discount = this.discountValue;
  }

  // Discount cannot exceed order amount
  return Math.min(discount, orderAmount);
};

// Method to calculate commission for an order
influencerSchema.methods.calculateCommission = function (finalAmount) {
  if (this.commissionType === "PERCENT") {
    return (finalAmount * this.commissionValue) / 100;
  }
  return this.commissionValue;
};

const InfluencerModel = mongoose.model("Influencer", influencerSchema);

export default InfluencerModel;
