runtime: nodejs22
service: admin

build_env_variables:
  NEXT_PUBLIC_API_URL: "https://healthy-one-gram.el.r.appspot.com"

env_variables:
  NEXT_PUBLIC_API_URL: "https://healthy-one-gram.el.r.appspot.com"